package mahjong.GUI;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import mahjong.GUI.utils.JTableModeleClassement;
import mahjong.joueur.Joueur;

/**
 * Gère la fenetre affichant la liste des joueurs avec leur meilleur temps et meilleur score.
 * 
 */
public class ClassementGUI extends javax.swing.JPanel {

    private final Fenetre fenetre;

    public ClassementGUI(Fenetre fenetre) {
        initComponents();
        this.fenetre = fenetre;
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                Point point = mouseEvent.getPoint();
                int row = jTable1.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2) {  
                    Joueur joueur = ((JTableModeleClassement) jTable1.getModel()).getListe().get(row);
                    PartieJoueurGUI GUIListeDePartie = new PartieJoueurGUI(fenetre, true, joueur);
                    GUIListeDePartie.setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonRetourMenu = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setText("Classement");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new JTableModeleClassement());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonRetourMenu.setText("Retour");
        jButtonRetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRetourMenu)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jButtonRetourMenu)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourMenuActionPerformed
        fenetre.afficherMenuPrincipal();
    }//GEN-LAST:event_jButtonRetourMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetourMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Actualise la liste des joueurs présent dans le tableau de classement
     */
    public final void rechargerListeJoueur() {
        for (int i = jTable1.getModel().getRowCount(); i > 0; i--) {
            ((JTableModeleClassement) jTable1.getModel()).retirerEntree(0);
        }
        
        fenetre.getGestionnaireJoueurs().getListeJoueurs().forEach((j) -> {
            ((JTableModeleClassement) jTable1.getModel()).ajouterEntree(j);
        });
    }
}
