package mahjong.GUI;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *  Classe gérant le menu principal du mahjong
 * 
 */
public class MenuPrincipal extends javax.swing.JPanel {

    private Fenetre fenetre;

    /**
     * Creates new form MenuPrincipal
     */

    MenuPrincipal(Fenetre fenetre) 
    {
        super();
        this.fenetre = fenetre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 60));
        boutonJouer = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 30), new java.awt.Dimension(10, 30));
        boutonChangerDeJoueur = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 30), new java.awt.Dimension(10, 30));
        boutonAccesClassement = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 30), new java.awt.Dimension(10, 30));
        boutonQuitter = new javax.swing.JButton();

        setAlignmentX(0.5F);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Mahjong");
        jLabel1.setAlignmentX(0.5F);
        add(jLabel1);
        add(filler1);

        boutonJouer.setText("Jouer");
        boutonJouer.setAlignmentX(0.5F);
        boutonJouer.setMaximumSize(new java.awt.Dimension(140, 35));
        boutonJouer.setMinimumSize(new java.awt.Dimension(140, 35));
        boutonJouer.setPreferredSize(new java.awt.Dimension(140, 35));
        boutonJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonJouerActionPerformed(evt);
            }
        });
        add(boutonJouer);
        add(filler2);

        boutonChangerDeJoueur.setText("Changer de joueur");
        boutonChangerDeJoueur.setAlignmentX(0.5F);
        boutonChangerDeJoueur.setMaximumSize(new java.awt.Dimension(140, 35));
        boutonChangerDeJoueur.setMinimumSize(new java.awt.Dimension(140, 35));
        boutonChangerDeJoueur.setPreferredSize(new java.awt.Dimension(140, 35));
        boutonChangerDeJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonChangerDeJoueurActionPerformed(evt);
            }
        });
        add(boutonChangerDeJoueur);
        add(filler3);

        boutonAccesClassement.setText("Classement");
        boutonAccesClassement.setAlignmentX(0.5F);
        boutonAccesClassement.setMaximumSize(new java.awt.Dimension(140, 35));
        boutonAccesClassement.setMinimumSize(new java.awt.Dimension(140, 35));
        boutonAccesClassement.setPreferredSize(new java.awt.Dimension(140, 35));
        boutonAccesClassement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAccesClassementActionPerformed(evt);
            }
        });
        add(boutonAccesClassement);
        add(filler4);

        boutonQuitter.setText("Quitter");
        boutonQuitter.setAlignmentX(0.5F);
        boutonQuitter.setMaximumSize(new java.awt.Dimension(140, 35));
        boutonQuitter.setMinimumSize(new java.awt.Dimension(140, 35));
        boutonQuitter.setPreferredSize(new java.awt.Dimension(140, 35));
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });
        add(boutonQuitter);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonJouerActionPerformed
        if(fenetre.getGestionnaireJoueurs().getJoueur()!=null)
        {
            CreationDePartie dialogueCreationDePartie = new CreationDePartie(fenetre, true);
            dialogueCreationDePartie.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Il n'y a aucun joueur de sélectionner", "Aucun joueur !", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boutonJouerActionPerformed

    /**
     * Permet d'afficher l'écran de selection du joueur
     * @param evt 
     */
    private void boutonChangerDeJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonChangerDeJoueurActionPerformed
        fenetre.afficherEcranSelectionJoueur();
    }//GEN-LAST:event_boutonChangerDeJoueurActionPerformed

    /**
     * Permet d'afficher l'écran de classement des joueurs
     * @param evt 
     */
    private void boutonAccesClassementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAccesClassementActionPerformed
        fenetre.afficherClassement();
    }//GEN-LAST:event_boutonAccesClassementActionPerformed

    /**
     * Permet de quitter le jeu
     * @param evt 
     */
    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        fenetre.dispatchEvent(new WindowEvent(fenetre, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_boutonQuitterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAccesClassement;
    private javax.swing.JButton boutonChangerDeJoueur;
    private javax.swing.JButton boutonJouer;
    private javax.swing.JButton boutonQuitter;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
