/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahjong.GUI;

import java.awt.Color;
import javax.swing.JProgressBar;
import mahjong.Plateau;

/**
 *
 * @author aschneid
 */
public class InterfaceDeJeu extends javax.swing.JPanel {
     /**
     * Creates new form InterfaceDeJeu
     */
    public InterfaceDeJeu() {
        plateauGUI = new PlateauGUI();
        initComponents();
    }

    public void setPlateau(Plateau plateau) {
        plateauGUI.setPlateau(plateau);
    }

    public void changerBarTemps(int temp, Color color) {
        jProgressBarTempsRestant.setValue(temp);
        jProgressBarTempsRestant.setForeground(color);
        jProgressBarTempsRestant.repaint();         //evite le saccadement
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoJeu = new javax.swing.JPanel();
        jProgressBarTempsRestant = new javax.swing.JProgressBar();
        jPanelInfoJoueur = new javax.swing.JPanel();
        jLabelLabelNomJoueur = new javax.swing.JLabel();
        labelNomJoueur = new javax.swing.JLabel();
        jLabelLabelScore = new javax.swing.JLabel();
        jLabelLabelTemps = new javax.swing.JLabel();
        labelScoreJoueur = new javax.swing.JLabel();
        labelTempPartie = new javax.swing.JLabel();
        plateauGUI = new mahjong.GUI.PlateauGUI();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanelInfoJeu.setMaximumSize(new java.awt.Dimension(200, 32767));

        jProgressBarTempsRestant.setOrientation(JProgressBar.VERTICAL);

        jLabelLabelNomJoueur.setText("Joueur :");

        labelNomJoueur.setText("jLabel2");

        jLabelLabelScore.setText("Score :");

        jLabelLabelTemps.setText("Temps :");

        labelScoreJoueur.setText("jLabel5");

        labelTempPartie.setText("jLabel6");

        javax.swing.GroupLayout jPanelInfoJoueurLayout = new javax.swing.GroupLayout(jPanelInfoJoueur);
        jPanelInfoJoueur.setLayout(jPanelInfoJoueurLayout);
        jPanelInfoJoueurLayout.setHorizontalGroup(
            jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoJoueurLayout.createSequentialGroup()
                .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoJoueurLayout.createSequentialGroup()
                        .addComponent(jLabelLabelNomJoueur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomJoueur))
                    .addGroup(jPanelInfoJoueurLayout.createSequentialGroup()
                        .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLabelScore)
                            .addComponent(jLabelLabelTemps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTempPartie)
                            .addComponent(labelScoreJoueur))))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanelInfoJoueurLayout.setVerticalGroup(
            jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoJoueurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelNomJoueur)
                    .addComponent(labelNomJoueur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelScore)
                    .addComponent(labelScoreJoueur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelTemps)
                    .addComponent(labelTempPartie))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelInfoJeuLayout = new javax.swing.GroupLayout(jPanelInfoJeu);
        jPanelInfoJeu.setLayout(jPanelInfoJeuLayout);
        jPanelInfoJeuLayout.setHorizontalGroup(
            jPanelInfoJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoJeuLayout.createSequentialGroup()
                .addComponent(jPanelInfoJoueur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarTempsRestant, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelInfoJeuLayout.setVerticalGroup(
            jPanelInfoJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBarTempsRestant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInfoJoueur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanelInfoJeu);

        javax.swing.GroupLayout plateauGUILayout = new javax.swing.GroupLayout(plateauGUI);
        plateauGUI.setLayout(plateauGUILayout);
        plateauGUILayout.setHorizontalGroup(
            plateauGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        plateauGUILayout.setVerticalGroup(
            plateauGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(plateauGUI);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLabelNomJoueur;
    private javax.swing.JLabel jLabelLabelScore;
    private javax.swing.JLabel jLabelLabelTemps;
    private javax.swing.JPanel jPanelInfoJeu;
    private javax.swing.JPanel jPanelInfoJoueur;
    private javax.swing.JProgressBar jProgressBarTempsRestant;
    private javax.swing.JLabel labelNomJoueur;
    private javax.swing.JLabel labelScoreJoueur;
    private javax.swing.JLabel labelTempPartie;
    private mahjong.GUI.PlateauGUI plateauGUI;
    // End of variables declaration//GEN-END:variables

    public void setTailleChronometre(int tempCoup) {
        jProgressBarTempsRestant.setMaximum(tempCoup);
    }

    public void updateTempJeu(String tempsTotalDeJeu) 
    {
        labelTempPartie.setText(tempsTotalDeJeu);
    }
}
